title: School of Ideas

tabs:
  pages:
    label: Seiten
    icon: page
    sections:
      pages:
        type: pages
        templates:
          - home
          - default
          - agenturen
          - agency
  settings:
    label: Einstellungen
    icon: settings
    fields:
      siteDescription:
        label: Meta Description
        type: textarea
        buttons: false
